apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.recommendation.releaseName  }}-service
  labels:
    app: {{ .Values.recommendation.releaseName  }}-app
    tier: web
spec:
  type:  {{ .Values.recommendation.service.type}}
  ports:
    - port: {{ .Values.blockchain.service.port}}
      targetPort: {{ .Values.recommendation.service.targetPort}}
  selector:
    app: {{ .Values.recommendation.releaseName  }}-app
