helm repo add bitnami https://charts.bitnami.com/bitnami
export mysqlRootPassword=...
export mysqlUser=...
export mysqlPassword=...
helm install mysql-twitter --set auth.rootPassword=${mysqlRootPassword},auth.username=${mysqlUser},auth.password=${mysqlPassword},auth.database=test bitnami/mysql --set image.debug=true \
--set primary.persistence.enabled=false,secondary.persistence.enabled=false \
--set primary.readinessProbe.enabled=false,primary.livenessProbe.enabled=false \
--set secondary.readinessProbe.enabled=false,secondary.livenessProbe.enabled=false
