apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: cluster.k8s.local
  name: nodes-us-east-1a
spec:
  # Note that if machine type is changed to ARM-based types, please change the image to:
  # 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20230830
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20230830
#  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-arm64-server-20230830
  machineType: m5.large
#  machineType: m6g.large
  maxSize: 5
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-us-east-1a
  role: Node
  rootVolumeSize: 32
  rootVolumeType: gp2
  subnets:
  - us-east-1a
