apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.qrcode.releaseName  }}-service
  labels:
    app: qrcode-app
    tier: web
spec:
  type:  {{ .Values.qrcode.service.type}}
  ports:
    - port: {{ .Values.qrcode.service.port}}
      targetPort: {{ .Values.qrcode.service.targetPort}}
  selector:
    app: qrcode-app
